# Generated by Django 5.2 on 2025-05-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
